

export enum IConferenceStatus {
  NOT_STARTED = 'NOT_STARTED',
  INTRODUCTION = 'INTRODUCTION',
  RUNNING = 'RUNNING',
  FINISHED = 'FINISHED'
}

export enum ITimeStatus {
  DEFAULT = 'DEFAULT',
  ENDING = 'ENDING',
  LAST_MINUTE = 'LAST_MINUTE',
  TIME_UP = 'TIME_UP'
}
