name: Frontend lint and style

on:
    pull_request:

    push:
        branches:
            - main

jobs:
    frontend-lint:
        name: Node ${{ matrix.node }}

        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: frontend

        strategy:
            matrix:
                node: ['17.4']

        steps:
            - name: Checkout the repository to Github workspace
              uses: actions/checkout@v2

            - name: Setup the Node environment
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install all NPM dependencies
              uses: bahmutov/npm-install@v1
              with:
                  working-directory: frontend

            - name: Run ESLint to ensure Javascript coding standards
              run: npx eslint src tests

            - name: Run Prettier to ensure Javascript styling
              run: npx prettier --check src tests
